# Generated by Django 5.1.7 on 2025-03-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacity (kg)'),
        ),
    ]
