# Generated by Django 4.2.6 on 2025-03-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weight', models.FloatField(verbose_name='Weight (kg)')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='Fragile')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity in Stock')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
